import { useEffect, useRef, useState } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { Toast } from './Toast';
import type { ToastVariant } from './Toast';
import { getFreshIdToken } from '../auth/freshIdToken';

const PIPELINE_BASE = import.meta.env.VITE_PIPELINE_API_BASE;
const POLL_INTERVAL_MS = 3000;
const TOAST_DURATION_MS = 5000;

const BUTTON_STYLE: React.CSSProperties = {
  position: 'fixed',
  top: 10,
  left: '50%',
  transform: 'translateX(-50%)',
  zIndex: 900,
  backgroundColor: 'white',
  padding: '8px 12px',
  borderRadius: 8,
  boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
  fontSize: 14,
  border: 'none',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  gap: 8,
};

// 'checking' = the POST round-trip, 'polling' = waiting on GET /pipeline/status
// for the run itself. Both spin the button: the POST returns almost immediately,
// so a spinner covering only that would flash for a fraction of a second and
// then leave the button looking idle for the minute-plus the pipeline actually
// takes. 'polling' is also entered without a click - see the mount effect.
type Status = 'idle' | 'checking' | 'polling';

// Triggers the pipeline's KML re-fetch/validate/upsert cycle. The backend
// (pipeline/app/main.py's POST /pipeline/run) does a fast lock-protected
// check-and-kickoff and returns immediately - the actual pipeline work runs
// afterward via FastAPI's BackgroundTasks, so this component polls
// GET /pipeline/status to learn when it finishes, rather than awaiting one
// long-lived request. This also means completion is detected the same way
// whether this click started the run, joined one already in progress, or
// (via the mount effect below) neither - some earlier, now-abandoned
// session's run is still going when this component first mounts.
export function RefreshDataButton() {
  const { getAccessTokenSilently, getIdTokenClaims, loginWithRedirect } = useAuth0();
  const [status, setStatus] = useState<Status>('idle');
  const [toast, setToast] = useState<{ variant: ToastVariant; message: string } | null>(null);
  const pollTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const toastTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (pollTimeoutRef.current) clearTimeout(pollTimeoutRef.current);
      if (toastTimeoutRef.current) clearTimeout(toastTimeoutRef.current);
    };
  }, []);

  function showToast(variant: ToastVariant, message: string, reloadAfter = false) {
    if (toastTimeoutRef.current) clearTimeout(toastTimeoutRef.current);
    setToast({ variant, message });
    toastTimeoutRef.current = setTimeout(() => {
      setToast(null);
      if (reloadAfter) window.location.reload();
    }, TOAST_DURATION_MS);
  }

  async function authHeader() {
    const token = await getFreshIdToken({ getAccessTokenSilently, getIdTokenClaims, loginWithRedirect });
    return { Authorization: `Bearer ${token}` };
  }

  async function fetchStatus() {
    const res = await fetch(`${PIPELINE_BASE}/pipeline/status`, { headers: await authHeader() });
    if (!res.ok) throw new Error(`status check failed: ${res.status}`);
    return res.json() as Promise<{
      running: boolean;
      last_result: 'success' | 'error' | null;
      last_details: {
        inserted: number;
        updated: number;
        unverified: number;
        unverified_lines: number;
      } | null;
    }>;
  }

  function pollUntilDone() {
    setStatus('polling');
    const poll = async () => {
      try {
        const s = await fetchStatus();
        if (s.running) {
          pollTimeoutRef.current = setTimeout(poll, POLL_INTERVAL_MS);
          return;
        }
        setStatus('idle');
        if (s.last_result === 'success') {
          // 未確認 = locations that fell back to a mechanical tier instead of a
          // reviewed entry - the schedule from app/hours.py's rule parser, the
          // line breaks from app/display.py's fallback. Both fail confidently
          // rather than loudly, so the counts are surfaced here instead of left
          // to be noticed. One headline number with the split behind it, since
          // the two are regenerated by different commands. Reported even when
          // zero: a silent toast is ambiguous between "nothing needs review" and
          // "the count stopped working".
          const inserted = s.last_details?.inserted ?? 0;
          const unverified = s.last_details?.unverified ?? 0;
          const unverifiedLines = s.last_details?.unverified_lines ?? 0;
          const review = unverified + unverifiedLines;
          showToast(
            'success',
            `更新が完了しました。\n（新規${inserted}件 / 未確認${review}件`
              + (review > 0 ? `：営業時間${unverified} / 表示${unverifiedLines}` : '')
              + `）\nページをリロードします。`,
            true,
          );
        } else {
          showToast('error', '更新中にエラーが発生しました。');
        }
      } catch {
        pollTimeoutRef.current = setTimeout(poll, POLL_INTERVAL_MS);
      }
    };
    poll();
  }

  // on mount: a run from some earlier, now-abandoned session may still be
  // in progress - regain visibility into it without requiring a click
  useEffect(() => {
    (async () => {
      try {
        const s = await fetchStatus();
        if (s.running) {
          showToast('info', '更新処理がすでに実行中です。\nしばらくお待ちください。');
          pollUntilDone();
        }
      } catch {
        // no auth yet / transient failure - a manual click still works
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleClick() {
    setStatus('checking');
    try {
      const res = await fetch(`${PIPELINE_BASE}/pipeline/run`, {
        method: 'POST',
        headers: await authHeader(),
      });
      const body = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(body.detail ?? `pipeline trigger failed: ${res.status}`);

      if (body.status === 'already_running') {
        showToast('info', '更新処理がすでに実行中です。\nしばらくお待ちください。');
      } else {
        showToast('info', 'データ更新を開始しました。\nしばらくお待ち下さい。');
      }
      // no setStatus('idle') between the two - pollUntilDone() takes the button
      // straight from 'checking' to 'polling' so the spinner never blinks off
      pollUntilDone();
    } catch {
      setStatus('idle');
      showToast('error', '更新中にエラーが発生しました。');
    }
  }

  return (
    <>
      <button
        style={status === 'idle' ? BUTTON_STYLE : { ...BUTTON_STYLE, cursor: 'default' }}
        onClick={handleClick}
        disabled={status !== 'idle'}
      >
        {status !== 'idle' && <span className="spinner" />}
        データ更新
      </button>
      {toast && <Toast variant={toast.variant} message={toast.message} />}
    </>
  );
}
